export const draftResultsByYear = {
    2025: [
        // round, pick, teamId, player, position, nflTeam
        [1, 1, "team-10", "Saquon Barkley", "RB", "PHI" ],
        [1, 2, "team-12", "Ja'Marr Chase", "WR", "CIN"],
        [1, 3, "team-1", "Bijan Robinson", "RB", "ATL"],
        [1, 4, "team-9", "Jahmyr Gibbs", "RB", "DET"],
        [1, 5, "team-6", "Chase Brown", "RB", "CIN"],
        [1, 6, "team-7", "CeeDee Lamb", "WR", "DAL"],
        [1, 7, "team-5", "Malik Nabers", "WR", "NYG"],
        [1, 8, "team-3", "Christian McCaffrey", "RB", "SF"],
        [1, 9, "team-11", "Nico Collins", "WR", "HOU"],
        [1, 10, "team-8", "Ashton Jeanty", "RB", "LV"],
        [1, 11, "team-2", "Brock Bowers", "TE", "LV"],
        [1, 12, "team-4", "Amon-Ra St. Brown", "WR", "DET"],

        [2, 1, "team-4", "Bucky Irving", "RB", "TB"],
        [2, 2, "team-2", "Derrick Henry", "RB", "BAL"],
        [2, 3, "team-8", "Brian Thomas Jr.", "WR", "JAX"],
        [2, 4, "team-11", "Drake London", "WR", "ATL"],
        [2, 5, "team-3", "A.J. Brown", "WR", "PHI"],
        [2, 6, "team-5", "Jonathan Taylor", "RB", "IND"],
        [2, 7, "team-7", "Ladd McConkey", "WR", "LAC"],
        [2, 8, "team-6", "Jaxon Smith-Njigba", "WR", "SEA"],
        [2, 9, "team-9", "Josh Jacobs", "RB", "GB"],
        [2, 10, "team-1", "Trey McBride", "TE", "ARI"],
        [2, 11, "team-12", "James Cook", "RB", "BUF"],
        [2, 12, "team-10", "Josh Allen", "QB", "BUF"],

        [3, 1, "team-10", "Mike Evans", "WR", "TB" ],
        [3, 2, "team-12", "Tee Higgins", "WR", "CIN"],
        [3, 3, "team-1", "Tyreek Hill", "WR", "MIA"],
        [3, 4, "team-9", "Terry McLaurin", "WR", "WAS"],
        [3, 5, "team-6", "Jalen Hurts", "QB", "PHI"],
        [3, 6, "team-7", "Lamar Jackson", "QB", "BAL"],
        [3, 7, "team-5", "Davante Adams", "WR", "LAR"],
        [3, 8, "team-3", "Isiah Pacheco", "RB", "KC"],
        [3, 9, "team-11", "Omarion Hampton", "RB", "LAC"],
        [3, 10, "team-8", "George Kittle", "TE", "SF"],
        [3, 11, "team-2", "Joe Burrow", "QB", "CIN"],
        [3, 12, "team-4", "Marvin Harrison Jr.", "WR", "ARI"],

        [4, 1, "team-4", "Xavier Worthy", "WR", "KC"],
        [4, 2, "team-2", "Alvin Kamara", "RB", "NO"],
        [4, 3, "team-8", "Chuba Hubbard", "RB", "CAR"],
        [4, 4, "team-11", "Garrett Wilson", "WR", "NYJ"],
        [4, 5, "team-3", "Courtland Sutton", "WR", "DEN"],
        [4, 6, "team-5", "James Conner", "RB", "ARI"],
        [4, 7, "team-7", "Kenneth Walker III", "RB", "SEA"],
        [4, 8, "team-6", "Treveyon Henderson", "RB", "NE"],
        [4, 9, "team-9", "D.J. Moore", "WR", "CHI"],
        [4, 10, "team-1", "DK Metcalf", "WR", "PIT"],
        [4, 11, "team-12", "Breece Hall", "RB", "NYJ"],
        [4, 12, "team-10", "George Pickens", "WR", "DAL"],

        [5, 1, "team-10", "David Montgomery", "RB", "DET" ],
        [5, 2, "team-12", "Baker Mayfield", "QB", "TB"],
        [5, 3, "team-1", "Bo Nix", "QB", "DEN"],
        [5, 4, "team-9", "Tetairoa McMillan", "WR", "CAR"],
        [5, 5, "team-6", "Jameson Williams", "WR", "DET"],
        [5, 6, "team-7", "Calvin Ridley", "WR", "TEN"],
        [5, 7, "team-5", "Devonta Smith", "WR", "PHI"],
        [5, 8, "team-3", "Justin Herbert", "QB", "LAC"],
        [5, 9, "team-11", "D'Andre Swift", "RB", "CHI"],
        [5, 10, "team-8", "RJ Harvey", "RB", "DEN"],
        [5, 11, "team-2", "Stefon Diggs", "WR", "NE"],
        [5, 12, "team-4", "Travis Kelce", "TE", "KC"],

        [6, 1, "team-4", "Tyrone Tracy", "RB", "NYG"],
        [6, 2, "team-2", "Jerry Jeudy", "WR", "CLE"],
        [6, 3, "team-8", "T.J. Hockenson", "TE", "MIN"],
        [6, 4, "team-11", "Jaylen Waddle", "WR", "MIA"],
        [6, 5, "team-3", "David Njoku", "TE", "CLE"],
        [6, 6, "team-5", "Mark Andrews", "TE", "BAL"],
        [6, 7, "team-7", "Tony Pollard", "RB", "TEN"],
        [6, 8, "team-6", "Zay Flowers", "WR", "BAL"],
        [6, 9, "team-9", "Tucker Kraft", "TE", "GB"],
        [6, 10, "team-1", "Aaron Jones", "RB", "MIN"],
        [6, 11, "team-12", "Chris Olave", "WR", "NO"],
        [6, 12, "team-10", "Evan Engram", "TE", "DEN"],

        [7, 1, "team-10", "Jake Bates", "K", "DET" ],
        [7, 2, "team-12", "Dalton Kincaid", "TE", "BUF"],
        [7, 3, "team-1", "Harrison Butker", "K", "KC"],
        [7, 4, "team-9", "Brock Purdy", "QB", "SF"],
        [7, 5, "team-6", "Jared Goff", "QB", "DET"],
        [7, 6, "team-7", "Rashee Rice", "WR", "KC"],
        [7, 7, "team-5", "Patrick Mahomes", "QB", "KC"],
        [7, 8, "team-3", "Trevor Lawrence", "QB", "JAX"],
        [7, 9, "team-11", "Kyler Murray", "QB", "ARI"],
        [7, 10, "team-8", "Matthew Golden", "WR", "GB"],
        [7, 11, "team-2", "Rome Odunze", "WR", "CHI"],
        [7, 12, "team-4", "Travis Hunter", "WR", "JAX"],
    ]
}